import Head from 'next/head'
import Image from 'next/image'
import {useState, useRef} from 'react'
import styles from '../styles/Home.module.css'
import { getAuth, signInWithEmailAndPassword, createUserWithEmailAndPassword  } from "firebase/auth";
import { initializeApp } from "firebase/app";
//import { getAnalytics } from "firebase/analytics";
// TODO: Add SDKs for Firebase products that you want to use
// https://firebase.google.com/docs/web/setup#available-libraries

// Your web app's Firebase configuration
// For Firebase JS SDK v7.20.0 and later, measurementId is optional
const firebaseConfig = {
  apiKey: "AIzaSyDCXlaeLS6qhg9JVk_VsDi_b89tFWTs-Sk",
  authDomain: "student-arrival.firebaseapp.com",
  projectId: "student-arrival",
  storageBucket: "student-arrival.appspot.com",
  messagingSenderId: "462546293872",
  appId: "1:462546293872:web:c108133388fffafaf950b5",
  measurementId: "G-P45DJJNDBY"
};

// Initialize Firebase

//const analytics = getAnalytics(app);


export default function Home() {
  {/*const [emailR, setEmail] = useState('')
const [passR, setPass] = useState('')*/}

  const emailRef = useRef(null)
  const passwordRef = useRef(null)
  
  const app = initializeApp(firebaseConfig);
  const auth = getAuth();

  const signin = event=>{
    event.preventDefault();
    createUserWithEmailAndPassword(auth,emailRef, passwordRef)
        .then(user =>{
          console.log(user)
        }).catch(err =>{
          console.log(err)
        })
  }

  const login =event=>{
    event.preventDefault()

    signInWithEmailAndPassword(auth, emailRef, passwordRef)
      .then(user => {
        // Signed in 
        console.log(user)

        // ...
      })
      .catch(error => {
        console.log(error)
      });
  }

  {/*const handleEmail=(event)=>{
    event.preventDefault()
    event.target.name==='email'?setEmail(event.target.value):emailR;
  }*.}

  {/*const handlePassword=(event)=>{
      event.preventDefault()
      event.target.name==='password'? setPass(event.target.value):passR;
  }*/}

  return (
    <div className={styles.container}>
      <Head>
        <title>Sign In</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

      <div className={styles.form}>
          <label>Email</label>
          <input ref={emailRef}></input>

          <label>Password</label>
          <input ref={passwordRef} ></input>

          <button onClick={signin}>signin</button>
      </div>

      </main>

      <footer className={styles.footer}>
        
      </footer>
    </div>
  )
}
